services:
  neo4j:
    image: neo4j:latest
    container_name: graphleague_db
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Database connection
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    volumes:
      - ./neo4j_data:/data

  streamlit_app:
    build: .
    container_name: graphleague_coach
    ports:
      - "8501:8501"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_USER=neo4j

      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - neo4j